version: '3.8'

services:
  screener-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_screener
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
